language: clojure
lein: 2.8.1
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - make $TARGET
env:
  matrix:
    - VERSION=1.7 TARGET=test
    - VERSION=1.8 TARGET=test
    - VERSION=1.9 TARGET=test
  global:
    - secure: "iCEGZ+qtXJVJ2P0npITCu6xSDprtrZVAm3tysJQ9Oj0Zvw3oyVL/Gg4ma3JDm+CAL0zPAmlPsi4OroCvE6qQILNYx3mWt0yBkwn6rbr4K7hoT6IRl8IBJ+MSbxrhi+qnKsWCawbhzYkyCwNR4CHKU+Vjud3kuDBebg04/ZaJgKE/9ZR1ztjsmLHN9Jb250e9Df6SXDJ9/LOV3Ryd+xNb15JZ+0xVeSu6VPoJkL+wKEImhH6lcnUexAQP/YOKFf1o2nzpZd/qyL3PUbi6DWR0cQg+WlanhrFPfh3TeznDabshLRQ7PZegtXDRmI1e33shRkvF4eWL2JzTgk7Ya4OWX/VxHrv30XanWftDiKhtX8yGsn47t56auCfIdSqvLE7CAHZDCpEM77yN5ZwRk6YDo/HeexRGBgMPPRfDibQJqictGdanYLvx0aCooYOAU8wSqtsYNAiufpVmSEf8fyuNzYVegTtUo3EWMJKhZr57dVEDDjpy2qzn1ISn8csK9nTcTvBYyGiXqAzmzuMsB/KtoQZlwbBLFiQbQ4wJ07TWc22Q9P9Kf8fbntLpgMR65CXWn8ElcF0iCJJv/q8X7I0IQwowHRN8cszuI5P+2adg9HZYGtBVB8egcuhqeK5ed7a6zpE0BWgeVtKQzZP88fAV+LvdLUlN+6CRVx5GG4b3UnY="
    - secure: "mWwmQu1oy0BlcYJ8lfqc7gBIpNugOOBLoyMpFqWPG1Cbfv+S57YOD9P6twJOZKpFvaCSZk22G8S0kKjCtgc3Hf3iEdp/JcnvGnZo42Cdz6YccXY8+59aaDVhZ41kwsjZSvWR3ZCvFC48px3ExLpAUiI8BO9Yr2vAU8HZ5adZxxCNtjBGflE2agIi8K92FUjKPKWkOxDwElQ0RhtS9tsATHm08U579IMnV3ns9PTGqD3bySUkQRGPHakCSsa0+7Blu75+k7sre3tP/YExr7sJzkly4NbQrViLYASGXYiL9/2ufU8jWePSGhb74dRO68nYq9jMg9/iw3rLTYXZBIi/6dhTDYhAGm4ba7RZfT/o5MtDUUQFZJT/eMDp5EsFRS6AofzzKjBrfjrbBY3Z2aEZppEX/L5lpFH60oc6tHLXseQiSAIN5yuqBjYaKMVTPWEtD5kIKmSyq0VhWrElU4AkQKSWYncFHYpcMZeVpNeZXC4GqDtXkXQv2k6NYorx9+xY1isUOOOre3i52kHvBDPB06WjrDmDNrSX8D0LE+0h8DdUvCKUHy1lP9FcGV7hezdHq+QfT/MdidRrAzAbs64cToOfYTMFxS8sXFIT3FreMze4FkTzTBw/HoWLxkRFRvDC6F85lxbiDuherXa/+jpKsZSsvKW5d80h5EgT1qs1ig0="
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9
stages:
  - name: test
  - name: check
  - name: deploy
    if: branch = master
jobs:
  include:
    # Test Clojure master against a single JDK
    - env: VERSION=master TARGET=test
      jdk: oraclejdk8

    # Coverage analysis
    - env: VERSION=1.9 TARGET=cloverage
      jdk: oraclejdk8
      after_success:
      - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

    # Eastwood linter
    - stage: check
      env: VERSION=1.9 TARGET=eastwood
      jdk: oraclejdk8

    # Check cljfmt
    - stage: check
      env: VERSION=1.9 TARGET=cljfmt
      jdk: oraclejdk8

    # Deployment
    - stage: deploy
      env: TARGET=deploy
      jdk: oraclejdk8

  allow_failures:
    - env: VERSION=master TARGET=test
